### ISSUE TITLE
I am unable to get any output on Display and only shows white screen.

### ISSUE THREAD

**Issue by bil7317** [0015/ESP32Berry#1]
### My setup:
Arduino IDE
ESP-32
ILI9488

### Previous experience: 
I have already interfaced ILI9488 with esp32 by following steps from your "Simple Note App Tutorial" and created a custom UI using LVGL and am familiar with Squareline Studio.

### Issue and steps taken:

1. I have tried Arduino IDE but am getting this error: `esp_netif.h: No such file or directory`
2. I have also tried `VS Code (PlateformIO)` but when I upload code to esp, the serial print is working but the display is not working. 
3. I have also tried to copy-paste TFT_eSPI folder in the PlateformIO libraries folder with proper `"User Setup"` changes but still, I am not getting anything on the screen. 
4. I have also tried installing the TFT_eSPI library in this project but I get the error of `SPIFFS.h not found`. I have even tried to add SPIFFS.h files in the `"include"` folder of the project but still no progress.

Kindly let me know which ide you are using:

**Comment by 0015** [comment]
@bil7317 Ok. First, check your ESP-IDF version. esp_netif.h is in the latest version of the components. 
https://github.com/espressif/esp-idf/blob/master/components/esp_netif/include/esp_netif.h

Why don't you use LovyanGFX instead of TFT_eSPI? Any reasons? LovyanGFX is much faster than TFT_eSPI. Also, I didn't have a test using TFT_eSPI for this project. I have no idea why TFT_eSPI issues are related to SPIFFS.

I don't use PlatformIO in my whole project so I don't know how works. Please check its forum to use Arduino Project in PlatformIO properly.

**Comment by bil7317** [comment]
I was making a childish mistake. I was previously working with TFT_eSPI so I assumed that this project is also based on it. I was also making mistakes in pin configuration for LovyanGFX. Thank you for your response. It is working fine now.

**Comment by 0015** [comment]
@bil7317 Sorry for the late reply. I thought it was related to using SNTP. Seems like I was wrong. You can delete it and you don't need to use esp_netif_init(). It works fine without it. I'll remove it on the next version.
